# Generated by Django 4.2.4 on 2023-11-09 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_cartitem_in_progress_alter_cartitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
