# Generated by Django 4.2.4 on 2023-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0009_order_orderitem_remove_cart_in_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pictures'),
        ),
    ]
