# Generated by Django 4.2.4 on 2023-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='profile_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='profile_pictures'),
        ),
    ]
