# Generated by Django 4.2.4 on 2023-08-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellinggymequipment',
            name='photo',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='bestsellingsupplements',
            name='photo',
            field=models.FileField(upload_to='images'),
        ),
    ]
