# Generated by Django 4.2.4 on 2023-09-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_cartitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
