# Generated by Django 4.2.4 on 2023-11-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_alter_shippingaddress_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
