# Generated by Django 4.2.4 on 2023-11-09 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0006_cartitem_date_added_alter_shippingaddress_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
