# Generated by Django 4.2.4 on 2023-11-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0011_userpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
