# Generated by Django 4.2.4 on 2023-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0012_delete_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
